SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [preODS].[Paycom_Employees]
AS

SELECT
	CONVERT(NVARCHAR(50),[Employee_Code] ) [Employee_Code_K]
	,CONVERT(NVARCHAR(250),[Employee_Name]									)[Employee_Name]
	,CONVERT(NVARCHAR(50),[Firstname]										)[Firstname]
	,CONVERT(NVARCHAR(50),[Lastname]										)[Lastname]
	,CONVERT(NVARCHAR(50),[Middle_Name]										)[Middle_Name]
	,CONVERT(NVARCHAR(50),[Nickname]										)[Nickname]
	,CONVERT(NVARCHAR(50),[Department]										)[Department]
	,CONVERT(NVARCHAR(250),[Department_Desc]									)[Department_Desc]
	,CONVERT(NVARCHAR(50),[Division_Code]									)[Division_Code]
	,CONVERT(NVARCHAR(250),[Division_Desc]									)[Division_Desc]
	,CONVERT(NVARCHAR(max),[Labor_Allocation_Details]						)[Labor_Allocation_Details]
	,CONVERT(NVARCHAR(25),[Employee_Status]									)[Employee_Status]
	,CONVERT(NVARCHAR(100),[Position]										)[Position]
	,CONVERT(NVARCHAR(25),[DOL_Status]										)[DOL_Status]
	,CONVERT(NVARCHAR(25),[ACA_Status]										)[ACA_Status]
	,CONVERT(NVARCHAR(25),[Gender]											)[Gender]
	,CONVERT(NVARCHAR(150),[Street]											)[Street]
	,CONVERT(NVARCHAR(100),[City]											)[City]
	,CONVERT(NVARCHAR(10),[State]											)[State]
	,CONVERT(NVARCHAR(20),[Zipcode]											)[Zipcode]
	,CONVERT(NVARCHAR(50),[Primary_Phone]									)[Primary_Phone]
	,CONVERT(NVARCHAR(25),[Primary_Phone_Type]								)[Primary_Phone_Type]
	,CONVERT(NVARCHAR(50),[Secondary_Phone]									)[Secondary_Phone]
	,CONVERT(NVARCHAR(50),[Secondary_Phone_Type]							)[Secondary_Phone_Type]
	,CONVERT(NVARCHAR(50),[Exempt_Status]									)[Exempt_Status]
	,CONVERT(NVARCHAR(max),[Perc_Labor_Distribution_*]						)[Perc_Labor_Distribution_*]
	,CONVERT(NVARCHAR(50),[Work_Email]										)[Work_Email]
	,CONVERT(NVARCHAR(100),[Personal_Email]									)[Personal_Email]
	,CONVERT(int,[Age]												)[Age]
	,CONVERT(float,[Annual_Salary]									)[Annual_Salary]
	,CONVERT(float,[Scheduled_Pay_Period_Hours]						)[Scheduled_Pay_Period_Hours]
	,CONVERT(NVARCHAR(25),[Labor_Allocation_Profile]						)[Labor_Allocation_Profile]
	,CONVERT(NVARCHAR(100),[Document_Group]									)[Document_Group]
	,CONVERT(NVARCHAR(50),[Employee_Added]									)[Employee_Added]
	,CONVERT(NVARCHAR(50),[Hire_Date]										)[Hire_Date]
	,CONVERT(NVARCHAR(50),[Last_Pay_Change]									)[Last_Pay_Change]
	,CONVERT(NVARCHAR(50),[Leave_End]										)[Leave_End]
	,CONVERT(NVARCHAR(50),[Leave_Start]										)[Leave_Start]
	,CONVERT(NVARCHAR(50),[Part-Time_to_Full-Time_Date]						)[Part-Time_to_Full-Time_Date]
	,CONVERT(NVARCHAR(50),[Previous_Termination_Date]						)[Previous_Termination_Date]
	,CONVERT(NVARCHAR(50),[Rehire_Date]										)[Rehire_Date]
	,CONVERT(NVARCHAR(50),[RetireeTermDate]									)[RetireeTermDate]
	,CONVERT(NVARCHAR(50),[SeniorityDate]									)[SeniorityDate]
	,CONVERT(NVARCHAR(50),[Termination_Date]								)[Termination_Date]
	,CONVERT(NVARCHAR(100),[EEO1_Ethnicity]									)[EEO1_Ethnicity]
	,CONVERT(NVARCHAR(50),[CampusLocation]									)[CampusLocation]
	,CONVERT(NVARCHAR(10),[ContractHold]									)[ContractHold]
	,CONVERT(NVARCHAR(100),[Division]										)[Division]
	,CONVERT(NVARCHAR(100),[DivisionHead]									)[DivisionHead]
	,CONVERT(NVARCHAR(100),[DivisionHeadTitle]								)[DivisionHeadTitle]
	,CONVERT(NVARCHAR(50),[EEName]											)[EEName]
	,CONVERT(NVARCHAR(50),[FTE]												)[FTE]
	,CONVERT(float,[HourlyRate]										)[HourlyRate]
	,CONVERT(NVARCHAR(100),[HighestDegree]									)[HighestDegree]
	,CONVERT(NVARCHAR(100),[IndexJobDefinition]								)[IndexJobDefinition]
	,CONVERT(NVARCHAR(100),[Major1]											)[Major1]
	,CONVERT(NVARCHAR(100),[PositionStatus]									)[PositionStatus]
	,CONVERT(NVARCHAR(100),[StipendRoless]									)[StipendRoless]
	,CONVERT(NVARCHAR(50),[TotalComp]										)[TotalComp]
	,CONVERT(NVARCHAR(50),[textCampusLocation]								)[textCampusLocation]
	,CONVERT(NVARCHAR(100),[textInsSupportStaff]								)[textInsSupportStaff]
	,CONVERT(NVARCHAR(100),[textJobDefinition]								)[textJobDefinition]
	,CONVERT(BIT,0) AS IsDeleted
FROM [dbo].[tmp_PaycomUpload]
GO
