SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [preODS].[SeniorSystems_persons_address]
AS

SELECT DISTINCT
	CONVERT(NVARCHAR(50),[EntityNo]) [EntityNo_K]
	--,CONVERT(NVARCHAR(MAX),[StudentsBillingAccess_]) [StudentsBillingAccess_]
	,CONVERT(NVARCHAR(50),[Addresses_AddressNumber]) [AddressNumber_k]
	,CONVERT(NVARCHAR(500),[Addresses_Address1]) [Address1]
	,CONVERT(NVARCHAR(500),[Addresses_Address2]) [Address2]
	,CONVERT(NVARCHAR(500),[Addresses_Address3]) [Address3]
	,CONVERT(NVARCHAR(10),[Addresses_NotPublishAddressLines]) [NotPublishAddressLines]
	,CONVERT(NVARCHAR(50),[Addresses_City]) [City]
	,CONVERT(NVARCHAR(10),[Addresses_State]) [State]
	,CONVERT(NVARCHAR(25),[Addresses_Zip]) [Zip]
	,CONVERT(NVARCHAR(10),[Addresses_NotPublishCityStateZip]) [NotPublishCityStateZip]
	,CONVERT(NVARCHAR(50),[Addresses_HouseholdID]) [HouseholdID]
	,CONVERT(NVARCHAR(50),[Addresses_Country]) [Country]
	,CONVERT(NVARCHAR(10),[Addresses_NotPublishCountry]) [NotPublishCountry]
	,CONVERT(NVARCHAR(50),[Addresses_Phone]) [Phone]
	,CONVERT(NVARCHAR(10),[Addresses_NotPublishPhone]) [NotPublishPhone]
	,CONVERT(NVARCHAR(250),[Addresses_Email1]) [Email1]
	,CONVERT(NVARCHAR(10),[Addresses_NotPublishEmail1]) [NotPublishEmail1]
	,CONVERT(NVARCHAR(10),[Addresses_SendHouseholdEmail1]) [SendHouseholdEmail1]
	,CONVERT(NVARCHAR(250),[Addresses_Email2]) [Email2]
	,CONVERT(NVARCHAR(10),[Addresses_NotPublishEmail2]) [NotPublishEmail2]
	,CONVERT(NVARCHAR(10),[Addresses_SendHouseholdEmail2]) [SendHouseholdEmail2]
	,CONVERT(NVARCHAR(50),[Addresses_OtherNumberType1]) [OtherNumberType1]
	,CONVERT(NVARCHAR(50),[Addresses_OtherNumber1]) [OtherNumber1]
	,CONVERT(NVARCHAR(10),[Addresses_NotPublishOtherNumber1]) [NotPublishOtherNumber1]
	,CONVERT(NVARCHAR(50),[Addresses_OtherNumberType2]) [OtherNumberType2]
	,CONVERT(NVARCHAR(50),[Addresses_OtherNumber2]) [OtherNumber2]
	,CONVERT(NVARCHAR(10),[Addresses_NotPublishOtherNumber2]) [NotPublishOtherNumber2]
	,CONVERT(NVARCHAR(50),[Addresses_OtherNumberType3]) [OtherNumberType3]
	,CONVERT(NVARCHAR(50),[Addresses_OtherNumber3]) [OtherNumber3]
	,CONVERT(NVARCHAR(10),[Addresses_NotPublishOtherNumber3]) [NotPublishOtherNumber3]
	,CONVERT(NVARCHAR(50),[Addresses_OtherNumberType4]) [OtherNumberType4]
	,CONVERT(NVARCHAR(50),[Addresses_OtherNumber4]) [OtherNumber4]
	,CONVERT(NVARCHAR(10),[Addresses_NotPublishOtherNumber4]) [NotPublishOtherNumber4]
	,CONVERT(NVARCHAR(10),[Addresses_IsActive]) [IsActive]
	,CONVERT(NVARCHAR(50),[Addresses_ActiveFromDate]) [ActiveFromDate]
	,CONVERT(NVARCHAR(50),[Addresses_ActiveToDate]) [ActiveToDate]
	,CONVERT(NVARCHAR(50),[Addresses_AddressType]) [AddressType]
	,CONVERT(NVARCHAR(50),[Addresses_AddressCode]) [AddressCode]
	,CONVERT(NVARCHAR(50),[Addresses_InternalAddressCode]) [InternalAddressCode]
	,CONVERT(NVARCHAR(250),[Addresses_CompanyName]) [CompanyName]
	,CONVERT(NVARCHAR(10),[Addresses_NotPublishCompany]) [NotPublishCompany]
	,CONVERT(NVARCHAR(100),[Addresses_Occupation]) [Occupation]
	,CONVERT(NVARCHAR(100),[Addresses_JobTitle]) [JobTitle]
	,CONVERT(NVARCHAR(100),[Addresses_Industry]) [Industry]
	,CONVERT(NVARCHAR(MAX),[Addresses_Notes]) [Notes]
	,CONVERT(NVARCHAR(100),[Addresses_BillCode]) [BillCode]
	,CONVERT(NVARCHAR(10),[Addresses_IsSendGrades]) [IsSendGrades]
	,CONVERT(NVARCHAR(10),[Addresses_IsPrimaryAddress]) [IsPrimaryAddress]
	,CONVERT(NVARCHAR(10),[Addresses_IsEmergencyContact]) [IsEmergencyContact]
	,CONVERT(NVARCHAR(10),[Addresses_NotPublishEntireAddress]) [NotPublishEntireAddress]
	,CONVERT(NVARCHAR(10),[Addresses_IsAdditionalContact]) [IsAdditionalContact]
	,CONVERT(NVARCHAR(10),[Addresses_HasPendingChanges]) [HasPendingChanges]
	,CONVERT(NVARCHAR(10),[Addresses_IsPendingRecord]) [IsPendingRecord]
	,CONVERT(NVARCHAR(10),[Addresses_IsPendingDelete]) [IsPendingDelete]
	,CONVERT(NVARCHAR(50),[Addresses_AdditionalContactInfo_Name1EntityNo]) [Name1EntityNo]
	,CONVERT(NVARCHAR(100),[Addresses_AdditionalContactInfo_Name1Title]) [Name1Title]
	,CONVERT(NVARCHAR(100),[Addresses_AdditionalContactInfo_Name1FirstName]) [Name1FirstName]
	,CONVERT(NVARCHAR(100),[Addresses_AdditionalContactInfo_Name1MiddleName]) [Name1MiddleName]
	,CONVERT(NVARCHAR(100),[Addresses_AdditionalContactInfo_Name1LastName]) [Name1LastName]
	,CONVERT(NVARCHAR(50),[Addresses_AdditionalContactInfo_Name1Suffix]) [Name1Suffix]
	,CONVERT(NVARCHAR(100),[Addresses_AdditionalContactInfo_Name1PreferredName]) [Name1PreferredName]
	,CONVERT(NVARCHAR(300),[Addresses_AdditionalContactInfo_Name1FullName]) [Name1FullName]
	,CONVERT(NVARCHAR(100),[Addresses_AdditionalContactInfo_Name1Relation]) [Name1Relation]
	,CONVERT(NVARCHAR(50),[Addresses_AdditionalContactInfo_Name2EntityNo]) [Name2EntityNo]
	,CONVERT(NVARCHAR(100),[Addresses_AdditionalContactInfo_Name2Title]) [Name2Title]
	,CONVERT(NVARCHAR(100),[Addresses_AdditionalContactInfo_Name2FirstName]) [Name2FirstName]
	,CONVERT(NVARCHAR(100),[Addresses_AdditionalContactInfo_Name2MiddleName]) [Name2MiddleName]
	,CONVERT(NVARCHAR(100),[Addresses_AdditionalContactInfo_Name2LastName]) [Name2LastName]
	,CONVERT(NVARCHAR(50),[Addresses_AdditionalContactInfo_Name2Suffix]) [Name2Suffix]
	,CONVERT(NVARCHAR(100),[Addresses_AdditionalContactInfo_Name2PreferredName]) [Name2PreferredName]
	,CONVERT(NVARCHAR(300),[Addresses_AdditionalContactInfo_Name2FullName]) [Name2FullName]
	,CONVERT(NVARCHAR(100),[Addresses_AdditionalContactInfo_Name2Relation]) [Name2Relation]
FROM [src].[SeniorSystems_persons] WITH (NOLOCK)
WHERE Addresses_AddressNumber IS NOT NULL
--order by 2

GO
