CREATE TABLE [import].[Senior_GPA_History]
(
[SCHOOL_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCHOOL_ID_SORT] [float] NULL,
[ACADEMIC_YR] [float] NULL,
[STUDENT_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_01] [float] NULL,
[GPA_02] [float] NULL,
[GPA_03] [float] NULL,
[GPA_04] [float] NULL,
[GPA_05] [float] NULL,
[GPA_06] [float] NULL,
[GPA_07] [float] NULL,
[GPA_08] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_09] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_10] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_11] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_12] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_13] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_14] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_15] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_16] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_17] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_18] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_21] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_22] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_23] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_24] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_25] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_26] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_27] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_28] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_29] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_30] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_31] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_32] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_33] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_34] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_35] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_36] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_37] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_38] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_39] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_40] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_41] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_42] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_43] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_44] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_45] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_46] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_47] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_48] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_49] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_50] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
