CREATE TABLE [import].[Senior_Grades_MS_8_A_RG_V2]
(
[ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SORT_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRST_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MIDDLE_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUFFIX] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FULL_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PREFERRED_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BOARD_DAY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEX_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ENTERED_DATE] [datetime] NULL,
[GRADE_ENTERED] [float] NULL,
[GRADE_ENTERED_SORT] [float] NULL,
[CURRENT_GRADE] [float] NULL,
[CURRENT_GRADE_SORT] [float] NULL,
[NEXT_SCHOOL_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NEXT_GRADE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NEXT_GRADE_SORT] [float] NULL,
[GRADE_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REPEATING_GRADE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADMISSIONS_YR] [float] NULL,
[CLASS_YR] [float] NULL,
[WITHDRAW_DATE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WITHDRAW_REASON] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REENTER_DATE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BIRTH_DATE] [datetime] NULL,
[BIRTH_COUNTRY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BIRTHPLACE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FULL_NAME_ALT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CITIZEN_COUNTRY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RACE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOC_SEC_NO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCHOOL_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCHOOL_ID_SORT] [float] NULL,
[ADVISOR_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADVISOR_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADVISOR_SORT_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HOMEROOM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HRTEACHER_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HRTEACHER_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HRTEACHER_SORT_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DORM_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DORM_ROOM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DORM_TEL_NO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COLLEGE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PREV_SCHOOL_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PREV_SCHOOL_FROM_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PREV_SCHOOL_TO_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PREV_SCH_SRT_KEY_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PREV_SCHOOL_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PREV_SCHOOL_FROM_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PREV_SCHOOL_TO_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PREV_SCH_SRT_KEY_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRAD_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIPLOMA_DATE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STUDENT_GROUP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STUDENT_GROUP_NO] [float] NULL,
[FAMILY_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RELIGION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHURCH] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RG_CUSTOM_FIELD_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RG_CUSTOM_FIELD_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RG_CUSTOM_FIELD_3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RG_CUSTOM_FIELD_4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RG_CUSTOM_FIELD_5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ST_CUSTOM_FIELD_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ST_CUSTOM_FIELD_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ST_CUSTOM_FIELD_3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ST_CUSTOM_FIELD_4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ST_CUSTOM_FIELD_5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IN_CHECK_PERIOD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LANGUAGE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ENTER_SCHOOL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ENTER_SCHOOL_SORT] [float] NULL,
[WITHDRAW_SCHOOL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WITHDRAW_SCH_SORT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DO_NOT_RANK] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ENROLL_STATUS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACADEMIC_YR] [float] NULL,
[SCHOOL_ID_COMPLETE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCHOOL_ATTENDED] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_COMPLETED] [float] NULL,
[GRADE_COMPLETE_SRT] [float] NULL,
[COURSE_ID] [float] NULL,
[SECTION_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SECTION_NO] [float] NULL,
[COURSE_NAME_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COURSE_NAME_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COURSE_FULL_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COURSE_ABBREV_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPARTMENT_ID] [float] NULL,
[DEPARTMENT_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIVISION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SECTION_GROUP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANS_GROUP_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANS_SUB_GRP_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANS_COURSE_ORDER] [float] NULL,
[CREDITS] [float] NULL,
[CREDITS_EARNED] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FACULTY_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FACULTY_FULL_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FACULTY_SORT_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TERM1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TERM2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TERM3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TERM4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TERM5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TERM6] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TERM7] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TERM8] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TERM9] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TERM10] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_MULTIPLIER] [float] NULL,
[ON_TRANSCRIPT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ON_GRADE_RPT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ON_GPA] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ON_GPA2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ON_GPA3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USE_QPA_VALUE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREDITS_TERM1] [float] NULL,
[CREDITS_TERM2] [float] NULL,
[CREDITS_TERM3] [float] NULL,
[CREDITS_TERM4] [float] NULL,
[CREDITS_TERM5] [float] NULL,
[CREDITS_TERM6] [float] NULL,
[CREDITS_TERM7] [float] NULL,
[CREDITS_TERM8] [float] NULL,
[CREDITS_TERM9] [float] NULL,
[CREDITS_TERM10] [float] NULL,
[CREDIT_FOR_TERM1] [float] NULL,
[CREDIT_FOR_TERM2] [float] NULL,
[CREDIT_FOR_TERM3] [float] NULL,
[CREDIT_FOR_TERM4] [float] NULL,
[CREDIT_FOR_TERM5] [float] NULL,
[CREDIT_FOR_TERM6] [float] NULL,
[CREDIT_FOR_TERM7] [float] NULL,
[CREDIT_FOR_TERM8] [float] NULL,
[CREDIT_FOR_TERM9] [float] NULL,
[CREDIT_FOR_TERM10] [float] NULL,
[CORE_COURSE_GROUP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COURSE_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ELECTIVE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CURRICULUM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COURSE_STATUS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COURSE_LEVEL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WD_PERIOD_NO] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WD_PERIOD_DESC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPA_BUMP_VALUE] [float] NULL,
[IS_HISTORY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_ROWID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_01] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_01] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_02] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_02] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_03] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_03] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_04] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_04] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_05] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_05] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_06] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_06] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_07] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_07] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_08] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_08] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_09] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_09] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_10] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_10] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_11] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_11] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_12] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_12] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_13] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_13] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_14] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_14] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_15] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_15] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_16] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_16] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_17] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_17] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_18] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_18] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_21] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_21] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_22] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_22] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_23] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_23] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_24] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_24] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_25] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_25] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_26] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_26] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_27] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_27] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_28] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_28] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_29] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_29] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_30] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_30] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_CHECK] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_CHECK] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LETTER_FINAL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMBER_FINAL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANS_GROUP_SORT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFFORT_MP1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFFORT_MP2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFFORT_MP3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFFORT_MP4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFFORT_MP5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFFORT_MP6] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFFORT_MP7] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFFORT_MP8] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFFORT_MP9] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFFORT_MP10] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFFORT_MPFINAL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFFORT_MPCHECK] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONDUCT_MP1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONDUCT_MP2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONDUCT_MP3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONDUCT_MP4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONDUCT_MP5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONDUCT_MP6] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONDUCT_MP7] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONDUCT_MP8] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONDUCT_MP9] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONDUCT_MP10] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONDUCT_MPFINAL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONDUCT_MPCHECK] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OTHER_MP1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OTHER_MP2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OTHER_MP3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OTHER_MP4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OTHER_MP5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OTHER_MP6] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OTHER_MP7] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OTHER_MP8] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OTHER_MP9] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OTHER_MP10] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OTHER_MPFINAL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OTHER_MPCHECK] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
