CREATE TABLE [ods].[Snapshot_Paycom_Employees]
(
[Paycom_EmployeesSK] [int] NOT NULL IDENTITY(1, 1),
[Employee_Code] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee_Name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Firstname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lastname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Middle_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nickname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Department] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Department_Desc] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Division_Code] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Division_Desc] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Labor_Allocation_Details] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee_Status] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Position] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOL_Status] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACA_Status] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zipcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary_Phone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary_Phone_Type] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Secondary_Phone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Secondary_Phone_Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Exempt_Status] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Perc_Labor_Distribution_*] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Work_Email] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Personal_Email] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age] [int] NULL,
[Annual_Salary] [float] NULL,
[Scheduled_Pay_Period_Hours] [float] NULL,
[Labor_Allocation_Profile] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Document_Group] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee_Added] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Hire_Date] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Pay_Change] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Leave_End] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Leave_Start] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Part-Time_to_Full-Time_Date] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Previous_Termination_Date] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rehire_Date] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RetireeTermDate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeniorityDate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Termination_Date] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EEO1_Ethnicity] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CampusLocation] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContractHold] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Division] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DivisionHead] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DivisionHeadTitle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EEName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FTE] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HourlyRate] [float] NULL,
[HighestDegree] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IndexJobDefinition] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Major1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PositionStatus] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StipendRoless] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalComp] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[textCampusLocation] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[textInsSupportStaff] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[textJobDefinition] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsDeleted] [bit] NULL,
[ETL_CreatedOn] [datetime] NULL,
[ETL_CreatedBy] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_UpdatedOn] [datetime] NULL,
[ETL_UpdatedBy] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecordEndDate] [datetime] NULL
)
GO
ALTER TABLE [ods].[Snapshot_Paycom_Employees] ADD CONSTRAINT [PK__Snapshot__98425F77902B4D7D] PRIMARY KEY CLUSTERED  ([Paycom_EmployeesSK])
GO
