CREATE TABLE [src].[Schoology_grade_items]
(
[SK] [bigint] NULL,
[ETL__multi_query_value_for_audit] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assignment_id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[title] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[due] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grading-scale] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grading-period] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grading-category] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[max-points] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[factor] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is-final] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[show-comments] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade-stats] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[allow-dropbox] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[allow-discussion] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[published] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[type] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade-item-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[available] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[completed] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dropbox-locked] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grading-scale-type] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[show-rubric] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[display-weight] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[folder-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[num-assignees] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last-updated] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[completion-status] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[topic-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
