CREATE TABLE [src].[BlackBaudFE_projects_project]
(
[SK] [bigint] NULL,
[ETL__multi_query_value_for_audit] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[project-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ui-project-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[start-date] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[end-date] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[location] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[division] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[department] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[type] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prevent-data-entry] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prevent-posting-after] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[posting-date] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[account-restrictions_allow-or-restrict] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[account-restrictions_criteria] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[custom-fields_custom-field-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[custom-fields_field-name] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[custom-fields_value] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[custom-fields_comments] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[custom-fields_type] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[custom-fields_date] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contacts_contact-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contacts_description] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contacts_country] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contacts_city] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contacts_county] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contacts_state] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contacts_address-line] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contacts_postal] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contacts_title] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contacts_first-name] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contacts_middle-name] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contacts_last-name] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contacts_suffix] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contacts_position] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address-contact-methods_] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address-contact-methods_contact-method-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address-contact-methods_contact-type] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address-contact-methods_contact-info] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
