CREATE TABLE [src].[BlackBaudFE_journalentrybatches_batch]
(
[SK] [bigint] NULL,
[ETL__multi_query_value_for_audit] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[batch-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ui-batch-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[batch-status] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[create-interfund-sets] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[create-bank-account-adjustments] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date-added] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[added-by] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date-modified] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modified-by] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[journal-entries_] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[journal-entry-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[type-code] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[line-number] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[account-number] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[post-date] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[encumbrance] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[journal] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[reference] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[amount] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[notes] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[distributions_] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[distributions_distribution-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[distributions_ui-project-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[distributions_account-class] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[distributions_amount] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[distributions_percent] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[custom-fields_custom-field-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[custom-fields_field-name] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[custom-fields_value] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[custom-fields_comments] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[custom-fields_type] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[custom-fields_date] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[distributions_transaction-code-values_] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[distributions_transaction-code-values_name] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[distributions_transaction-code-values_value] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
