CREATE TABLE [src].[Schoology_grades]
(
[SK] [bigint] NULL,
[ETL__multi_query_value_for_audit] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[final-grade_enrollment-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[period_period-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[period_period-title] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[period_weight] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[final-grade_scale-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade_enrollment-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade_assignment-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade_grade] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade_exception] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade_max-points] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade_is-final] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade_timestamp] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade_comment] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade_comment-status] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade_override] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade_calculated-grade] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade_pending] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade_type] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade_location] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade_scale-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade_scale-type] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade_category-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grade_school-uid] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[final-grade_period_period-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[final-grade_period_grade] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[final-grade_period_comment] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[final-grade_period_comment-status] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[final-grade_period_total-points-possible] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[final-grade_period_total-points-awarded] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[final-grade_period_override-numeric] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[final-grade_period_exception] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
