CREATE TABLE [src].[Schoology_users]
(
[SK] [bigint] NULL,
[ETL__multi_query_value_for_audit] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[uid] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Userid] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[school-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[synced] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[school-uid] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[building-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name-title] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name-title-show] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name-first] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name-first-preferred] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[use-preferred-first-name] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name-middle] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name-middle-show] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name-last] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name-display] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[username] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[primary-email] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[picture-url] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gender] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[position] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grad-year] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[password] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[role-id] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tz-offset] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tz-name] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parents] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[child-uids] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[language] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[additional-buildings] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bio] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[phone] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[subjects-taught] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[website] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grades-taught] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[interests] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bio-position] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[activities] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[department] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[birthday-date] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[birthday] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
